export const quotes: string[] = [
  'Nỗi buồn lớn nhất là cố tỏ ra hạnh phúc. Nỗi đau lớn nhất là luôn cố gắng mỉm cười',
  'Người ta nói rằng bạn không thể sống thiếu tình yêu. Nhưng tôi nghĩ oxi quan trọng hơn',
  'Bạn không mập. Chỉ là người ta dễ thấy bạn hơn thôi',
  'Hãy cẩn thận khi đọc sách về sức khỏe. Bạn có thể bỏ mạng vì một lỗi in ấn.',
  'Người ta nói tình yêu quan trọng hơn tiền bạc, nhưng bạn đã bao giờ thử thanh toán hóa đơn với một cái ôm chưa?',
  'Người đàn ông thành công là người kiếm được nhiều tiền hơn vợ mình có thể tiêu. Người phụ nữ thành công là người tìm ra được người đàn ông đó.',
  'Đừng bao giờ tin cái gì rỉ máu cả tuần lễ mà không chết ngóm.',
  'Đàn ông kết hôn vì họ mệt mỏi. Phụ nữ kết hôn vì họ tò mò. Cả hai đều thất vọng.',
  'Chỉ có 2 loại ngôn ngữ lập trình. Một loại bị nhiều người chê và một loại không ai thèm sử dụng.',
  'Nếu debug là quá trình loại bỏ bug trong phần mềm thì code chính là quá trình tạo ra nó',
  'Optimize code sớm là gốc rễ của mọi tội ác',
  'Thứ khó nhất trong ngành lập trình là đặt tên.',
  'Cho người ta một phần mềm, bạn sẽ làm họ bực mình một ngày. Dạy người ta lập trình, họ sẽ bực mình cả đời.',
  '9 người đàn bà không thể đẻ ra một đứa trẻ trong vòng một tháng.',
  'Hãy viết code như thể người maintain là một đứa sát nhân điên cuồng biết địa chỉ nhà bạn.',
  'Lập trình cũng như làm tình. Một bước sa chân là bạn phải chịu trách nhiệm cả đời',
  'Công việc của lập trình viên không phải là ngồi 8 tiếng một ngày để gõ code. Mà là làm cho thế giới trở nên tốt đẹp hơn.',
  'Fix bug là chuyện dễ. Tìm được đoạn code gây ra bug để fix mới là vấn đề.',
  'Debug là việc khó gấp đôi code. Nếu bạn code với mọi sự thông minh mà bạn có, bạn sẽ không thể debug nó.',
  'Máy tính là một cỗ máy ngu ngốc, có thể làm những điều vô cùng thông minh. Lập trình viên là những người thông minh, có thể làm những việc vô cùng ngu ngốc.',
  'Nếu 1 ly cafe vào buổi sáng chưa đủ giúp bạn tỉnh táo..., Hãy thử xóa 1 table trong database để thấy hiệu quả hơn.',
  'Ngôn ngữ là nhất thời, thuật toán là mãi mãi.'
];
